// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('app.user.ctrls', []).controller('invoicesCtrl', ['$scope', '$window']);

}).call(this);

//# sourceMappingURL=InvoicesCtrl.map
