// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('app.user.ctrls', []).controller('profileCtrl', ['$scope', '$window']);

}).call(this);

//# sourceMappingURL=ProfileCtrl.map
